Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 706, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Histogram
plt.figure(figsize=(10, 5))
sns.histplot(data[["sepal length","sepal width", "petal width"]], kde=True, bins=45, element='step', palette='tab10')
plt.title('Attribute Distributions in the Iris Dataset')
plt.xlabel('Values (cm)')
plt.ylabel('Frequency')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-5-823915e7989d>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Histogram[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m10[0m[0;34m,[0m [0;36m5[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0msns[0m[0;34m.[0m[0mhistplot[0m[0;34m([0m[0mdata[0m[0;34m[[0m[0;34m[[0m[0;34m"sepal length"[0m[0;34m,[0m[0;34m"sepal width"[0m[0;34m,[0m [0;34m"petal width"[0m[0;34m][0m[0;34m][0m[0;34m,[0m [0mkde[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mbins[0m[0;34m=[0m[0;36m45[0m[0;34m,[0m [0melement[0m[0;34m=[0m[0;34m'step'[0m[0;34m,[0m [0mpalette[0m[0;34m=[0m[0;34m'tab10'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'Attribute Distributions in the Iris Dataset'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mxlabel[0m[0;34m([0m[0;34m'Values (cm)'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'seaborn' has no attribute 'histplot'

